query getAlbumPhotoInfo($id: ID!, $options: PageQueryOptions) {
  album(id: $id) {
    id
    photos(options: $options) {
      data {
        id
        title
        thumbnailUrl
      }
      meta {
        totalCount
      }
    }
  }
}
